### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by yzq1234** [Heyu-cmd/SpERT-Aggcn#1]
、

**Comment by Heyu-cmd** [comment]
![Uploading 截屏 2024-02-14 14.32.16.jpeg…]()

**Comment by Heyu-cmd** [comment]
![截屏 2024-02-14 14 32 16](https://github.com/Heyu-cmd/SpERT-Aggcn/assets/53960215/8b64c2ea-8faa-49b5-ba99-0476f4d5f337)
